### ISSUE TITLE
Crash when clicking on team page from hall of fame

### ISSUE THREAD

**Issue by Mineinjava** [gryphonmachine/machine#40] opened 2023-05-16 15:44 UTC
**Describe the bug**
`Application error: a client-side exception has occurred (see the browser console for more information).` appears when clicking on a team number in the hall of fame

**Steps To Reproduce**
Steps to reproduce the crash if possible:

1. click `hall of fame`
2. Click on '254'

**Screenshots**
Add screenshots here to show any relevant information.
<img width="793" alt="image" src="https://github.com/scoutmachine/web/assets/65673396/afa9ae42-6169-4e05-9e9c-d90f17bb072d">

**Browser**

- OS: MacOS Ventura
- Browser: Safari Version 16.1 (18614.2.9.1.12)

**Additional context**
Console log:

https://gist.github.com/Mineinjava/99177b138312d7da985308df04091e8e

**Comment by Mineinjava** [comment] 2023-05-16 15:46
It appears that going to a team page, such as https://machine.frc6070.ca/teams/254 causes the same error.

**Comment by Autumn-Ou** [comment] 2023-05-16 18:42
This issue does not seem to exist on safari in iOS, I'll look into it more thank you.

**Comment by Autumn-Ou** [comment] 2023-05-16 18:43
Are you logged in when the error occurs or signed out/without an account?

**Comment by Mineinjava** [comment] 2023-05-16 19:49
I was not logged in.

**Comment by Autumn-Ou** [comment] 2023-05-16 19:58
That changes behaviour a bit, I'll check without being logged in on other platforms to see if the issue is present beyond MacOS for Safari & if it exists in other browsers. Thank you for reporting this.

**Comment by heybereket** [comment] 2023-05-16 21:30
Thanks for reporting this. Fixed as of 954fc964f73f0ec05976a8a1b550861a228cbe57. Looks like the code was trying to fetch `Team Members` only when a user was signed in.

**Closed as completed by heybereket** 2023-05-16 21:30 UTC
Labels: bug
